// Domain types for the Adaptive Interview Engine

/** Candidate profile and metadata */
/**
 * Candidate
 *
 * The external API (see AGENTS.md) supplies a candidate object but does not
 * prescribe a fixed schema. Preserve flexibility while keeping the type
 * strongly typed: allow an optional id and a freeform `profile` bag for
 * caller-provided fields. This avoids inventing fields while enabling the
 * engine to read profile signals when present.
 */
export interface Candidate {
  // Optional canonical identifier supplied by the caller
  id?: string;
  // A lightweight display name, if provided
  displayName?: string;
  // Arbitrary profile data supplied by the caller (do not assume structure)
  // Keep typed as Record<string, unknown> rather than `any` so callers must
  // validate specific fields before use.
  profile?: Record<string, unknown>;
}

/** The canonical interview stages (8 evidence objectives) */
export enum InterviewStage {
  Establish = "Establish",
  Build = "Build",
  Extend = "Extend",
  Break = "Break",
  Disambiguate = "Disambiguate",
  Optimize = "Optimize",
  Operate = "Operate",
  Synthesize = "Synthesize",
}

/** Evidence level for competencies */
export type EvidenceLevel = "strong" | "moderate" | "weak" | "none";

/** Competency buckets that an answer may provide evidence for */
export interface CompetencyEvidence {
  conceptual?: EvidenceLevel;
  implementation?: EvidenceLevel;
  systemDesign?: EvidenceLevel;
  debugging?: EvidenceLevel;
  edgeCases?: EvidenceLevel;
  tradeoffs?: EvidenceLevel;
  optimization?: EvidenceLevel;
  production?: EvidenceLevel;
  security?: EvidenceLevel;
}

/** Evidence produced by a candidate answer about a single question */
export interface Evidence {
  id: string; // unique id for this evidence item
  questionId: string;
  topic: string;
  competencies: CompetencyEvidence;
  observations: string[]; // concrete observations supporting the competency levels
  missing: string[]; // things the answer failed to mention that are important
  contradictions: string[]; // contradictions observed vs prior evidence or profile
  confidence: "low" | "medium" | "high";
  createdAt: string; // ISO timestamp
}

/** Uncertainties represent areas that require further investigation */
export interface Uncertainty {
  id: string;
  area: string; // e.g., "debugging", "RAG"
  reason: string; // why this uncertainty exists
  priority: "low" | "medium" | "high";
  relatedQuestionIds?: string[];
  createdAt: string;
}

/** Investigation is a planned question/objective for the engine to resolve an uncertainty */
export interface Investigation {
  id: string;
  objective: string;
  hypothesis: string;
  targetArea: string;
  priority?: "low" | "medium" | "high";
  relatedEvidenceIds?: string[];
  createdAt: string;
}

/** Question generated by the engine to ask the candidate */
export interface GeneratedQuestion {
  id: string;
  text: string;
  targetArea: string;
  curriculumDays: number[]; // numeric curriculum day ids
  purpose: string; // internal-only description of why this question exists
  difficulty?: "easy" | "medium" | "hard";
  createdAt: string;
}

/** Result of evaluating a candidate's answer */
export interface AnswerEvaluation {
  evaluationId: string;
  evidence: Evidence[];
  missing: string[];
  contradictions: string[];
  confidence: "low" | "medium" | "high";
  evaluatedAt: string;
}

/** Decision the deterministic engine will use next — discriminated union */
export type Decision =
  | {
      action: "CONTINUE_INVESTIGATION";
      investigation: Investigation;
    }
  | {
      action: "NEW_INVESTIGATION";
      investigation: Investigation;
    }
  | {
      action: "ADVANCE_STAGE";
      stage: InterviewStage;
    }
  | {
      action: "FINISH";
    };

/** Message role and content */
export type MessageRole = "candidate" | "interviewer" | "system";

export interface MessageBase {
  id: string;
  role: MessageRole;
  content: string;
  createdAt: string;
  // optional link to the question this message is answering or asking
  questionId?: string;
}

export type Message = MessageBase;

/** One interview turn: a question, the candidate's answer message, its evaluation and resulting decision */
export interface InterviewTurn {
  turnNumber: number;
  question?: GeneratedQuestion;
  answer?: Message; // typically role === 'candidate'
  evaluation?: AnswerEvaluation;
  decision?: Decision;
  timestamp: string;
}

/** The full interview session state */
export interface InterviewState {
  sessionId: string;
  candidate: Candidate;

  questionCount: number; // total questions asked so far
  stage: InterviewStage; // current interview stage

  evidence: Evidence[];
  uncertainties: Uncertainty[];
  investigations: Investigation[]; // planned or in-progress investigations

  coveredTopics: string[];
  coveredCurriculumDays: number[]; // which curriculum day ids have been covered

  askedQuestions: string[]; // question ids already asked (avoid duplicates)

  currentFocus?: Investigation;

  messages: Message[]; // chronological messages (questions and answers)
  turns: InterviewTurn[]; // chronological turns

  status: "active" | "completed";

  createdAt: string;
  updatedAt: string;
}
